// Package totp provides TOTP and recovery-code primitives,
// mirroring backend/src/auth/totp.py.
//
// TOTP parameters:
//   - Algorithm: SHA1 (pyotp default)
//   - Digits: 6 (pyotp default)
//   - Period: 30 s (pyotp default)
//   - Secret: base32 (pyotp.random_base32 → 32 chars = 160 bits by default,
//     but pquerna/otp GenerateKey produces 20 bytes = 160 bits = 32 base32 chars,
//     which is the same size pyotp produces, so they are cross-compatible)
//   - Valid window: ±1 step (totp.py: verify(code, valid_window=1))
//
// Recovery codes (totp.py generate_recovery_codes):
//   - Count: 10 (default n=10)
//   - Format: secrets.token_hex(5) → 10 hex chars (5 bytes)
//   - Hash: sha256(code.encode()).hexdigest() — stored as hex strings
//
// Cross-compat: the hash algorithm and secret format are byte-identical to
// Python, so codes generated by either backend verify against the other
// when sharing the same DB.
package totp

import (
	"bytes"
	"crypto/rand"
	"crypto/sha256"
	"crypto/subtle"
	"encoding/base64"
	"encoding/hex"
	"fmt"
	"image/png"

	"github.com/boombuler/barcode"
	"github.com/boombuler/barcode/qr"
	"github.com/pquerna/otp"
	gototp "github.com/pquerna/otp/totp"
)

// issuer is the default TOTP issuer label, matching totp.py provisioning_uri
// default issuer_name="WAF".
const defaultIssuer = "WAF"

// -----------------------------------------------------------------------
// Secret generation
// -----------------------------------------------------------------------

// GenerateSecret generates a random TOTP base32 secret compatible with pyotp.
// pyotp.random_base32() returns a 32-char (160-bit) base32 string by default.
// pquerna/otp generates a 20-byte (160-bit) random secret, encoded as 32 base32 chars.
func GenerateSecret() (string, error) {
	key, err := gototp.Generate(gototp.GenerateOpts{
		Issuer:      defaultIssuer,
		AccountName: "user",
		SecretSize:  20, // 20 bytes = 160 bits = 32 base32 chars (pyotp default)
		Algorithm:   otp.AlgorithmSHA1,
		Digits:      otp.DigitsSix,
		Period:      30,
	})
	if err != nil {
		return "", fmt.Errorf("totp: generate secret: %w", err)
	}
	return key.Secret(), nil
}

// -----------------------------------------------------------------------
// Provisioning URI
// -----------------------------------------------------------------------

// ProvisioningURI builds the otpauth:// URI, matching pyotp.TOTP.provisioning_uri.
//
// pyotp format: otpauth://totp/<issuer>:<accountName>?secret=<secret>&issuer=<issuer>
// pquerna/otp produces the identical format.
func ProvisioningURI(secret, accountName, issuer string) string {
	if issuer == "" {
		issuer = defaultIssuer
	}
	key, err := otp.NewKeyFromURL(
		fmt.Sprintf("otpauth://totp/%s:%s?secret=%s&issuer=%s&algorithm=SHA1&digits=6&period=30",
			issuer, accountName, secret, issuer),
	)
	if err != nil {
		// Fallback: build manually
		return fmt.Sprintf("otpauth://totp/%s:%s?secret=%s&issuer=%s&algorithm=SHA1&digits=6&period=30",
			issuer, accountName, secret, issuer)
	}
	return key.URL()
}

// QRDataURI renders the otpauth:// URI as a PNG QR code and returns it as a
// data: URI, mirroring totp.py qr_data_uri:
//
//	img = qrcode.make(uri); buf = BytesIO(); img.save(buf, "PNG")
//	return "data:image/png;base64," + base64(buf)
func QRDataURI(uri string) (string, error) {
	code, err := qr.Encode(uri, qr.M, qr.Auto)
	if err != nil {
		return "", fmt.Errorf("totp: qr encode: %w", err)
	}
	code, err = barcode.Scale(code, 256, 256)
	if err != nil {
		return "", fmt.Errorf("totp: qr scale: %w", err)
	}
	var buf bytes.Buffer
	if err := png.Encode(&buf, code); err != nil {
		return "", fmt.Errorf("totp: qr png encode: %w", err)
	}
	return "data:image/png;base64," + base64.StdEncoding.EncodeToString(buf.Bytes()), nil
}

// -----------------------------------------------------------------------
// Code verification
// -----------------------------------------------------------------------

// Verify checks whether code is valid for secret at the current time.
// Matches totp.py verify_code: pyotp.TOTP(secret).verify(code, valid_window=1)
// → accepts codes from t-1 step, current step, and t+1 step (skew tolerance).
func Verify(secret, code string) bool {
	if secret == "" || code == "" {
		return false
	}
	return gototp.Validate(code, secret)
}

// VerifyWithWindow is exposed for tests and matches the valid_window=1 behaviour
// (pquerna's Validate already uses a ±1 step window by default).
// This function is identical to Verify; it exists to make the parameter explicit.
func VerifyWithWindow(secret, code string) bool {
	return Verify(secret, code)
}

// -----------------------------------------------------------------------
// Recovery codes
// -----------------------------------------------------------------------

// GenerateRecoveryCodes generates n recovery codes and their SHA-256 hashes.
// Mirrors totp.py generate_recovery_codes:
//
//	plain  = [secrets.token_hex(5) for _ in range(n)]    # 10 hex chars each
//	hashes = [hashlib.sha256(c.encode()).hexdigest() for c in plain]
//
// Returns (plain_codes, sha256_hex_hashes).  The caller stores ONLY the hashes.
func GenerateRecoveryCodes(n int) (plain []string, hashed []string) {
	plain = make([]string, n)
	hashed = make([]string, n)
	buf := make([]byte, 5) // 5 bytes → 10 hex chars (token_hex(5))
	for i := range plain {
		if _, err := rand.Read(buf); err != nil {
			panic(fmt.Sprintf("totp: generate recovery code entropy: %v", err))
		}
		plain[i] = hex.EncodeToString(buf)
		hashed[i] = sha256Hex(plain[i])
	}
	return plain, hashed
}

// VerifyRecoveryCode checks whether code matches any entry in hashed.
// Returns (matchedIndex, true) on success, (-1, false) on failure.
// Mirrors totp.py verify_recovery (the hash lookup part, without DB write).
func VerifyRecoveryCode(code string, hashed []string) (matchedIndex int, ok bool) {
	h := sha256Hex(code)
	for i, stored := range hashed {
		// constant-time comparison to avoid timing side-channels
		if subtle.ConstantTimeCompare([]byte(h), []byte(stored)) == 1 {
			return i, true
		}
	}
	return -1, false
}

// sha256Hex returns the hex-encoded SHA-256 digest of s,
// matching Python's hashlib.sha256(code.encode()).hexdigest().
func sha256Hex(s string) string {
	sum := sha256.Sum256([]byte(s))
	return hex.EncodeToString(sum[:])
}
