name: waf
services:
  angie:
    build: configs/angie
    ports:
      - "80:80"
    volumes:
      - ./var/log/angie:/var/log/angie
      - ./configs/angie/angie.conf:/etc/angie/angie.conf
      - ./configs/angie/http.d/:/etc/angie/http.d/
      - ./configs/angie/modsecurity/:/etc/angie/modsecurity/
      - ./configs/angie/geoip2/:/etc/angie/geoip2/
    depends_on:
      - vector
    restart: unless-stopped
    env_file:
      - .env

  vector:
    image: timberio/vector:0.36.0-debian
    volumes:
      - ./var/log:/var/log
      - ./configs/vector/vector.yaml:/etc/vector/vector.yaml
    depends_on:
      - clickhouse
    restart: unless-stopped
    env_file:
      - .env

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./configs/clickhouse/init.sql:/docker-entrypoint-initdb.d/init.sql
      - clickhouse:/var/lib/clickhouse
    env_file:
      - .env

  grafana:
    image: grafana/grafana:latest
    entrypoint: ["/bin/sh", "-c", "sed -i \"s|__CLICKHOUSE_USER__|$$CLICKHOUSE_USER|g; s|__CLICKHOUSE_PASSWORD__|$$CLICKHOUSE_PASSWORD|g\" /etc/grafana/provisioning/datasources/clickhouse.yml && /run.sh"]
    ports:
      - "3001:3000"
    volumes:
    #   - ./etc/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./configs/grafana/provisioning:/etc/grafana/provisioning
      - grafana-storage:/var/lib/grafana
    depends_on:
      - clickhouse
    restart: unless-stopped
    env_file:
      - .env

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./configs/angie/modsecurity:/app/etc/angie/modsecurity
      - ./configs/angie/angie.conf:/app/etc/angie/angie.conf
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  clickhouse:
  grafana-storage: