services:
  angie:
    image: docker.angie.software/angie:templated
    ports:
      - "80:80"
    volumes:
      - ./angie/angie.conf:/etc/angie/angie.conf
      - angie-logs:/var/log/angie
    env_file:
      - ./envs/angie.env
    depends_on:
      - vector
    command: sh -c "rm /var/log/angie/access.log && angie -g 'daemon off;'"

  vector:
    image: timberio/vector:0.36.0-debian
    volumes:
      - ./vector/vector.yaml:/etc/vector/vector.yaml
      - /var/log:/var/log
      - vector-data:/var/lib/vector
      - angie-logs:/var/log/angie
    env_file:
      - ./envs/vector.env
    depends_on:
      - clickhouse

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./clickhouse/init.sql:/docker-entrypoint-initdb.d/init.sql
      - clickhouse-data:/var/lib/clickhouse
    env_file:
      - ./envs/clickhouse.env

volumes:
  angie-logs:
  clickhouse-data:
  vector-data: