package auth

import (
	"testing"

	"github.com/stretchr/testify/require"
)

// TestFernetRoundTrip verifies Go-encrypt → Go-decrypt is identity.
func TestFernetRoundTrip(t *testing.T) {
	key := testKey()
	const secret = "JBSWY3DPEHPK3PXP"

	tok, err := FernetEncrypt(key, secret)
	require.NoError(t, err)
	require.NotEqual(t, secret, tok)

	got, err := FernetDecrypt(key, tok)
	require.NoError(t, err)
	require.Equal(t, secret, got)
}

// TestFernetCrossDecryptPython decrypts a token produced by Python's
// cryptography.Fernet(base64.urlsafe_b64encode(paseto_key)) using the same
// 32-byte key (testKey() = 0x00..0x1f). This is the load-bearing cross-compat
// assertion: a TOTP secret encrypted by the Python backend must decrypt here.
//
// Vector generated by:
//
//	key_bytes = bytes(range(32))
//	f = Fernet(base64.urlsafe_b64encode(key_bytes))
//	f.encrypt(b"JBSWY3DPEHPK3PXP")
func TestFernetCrossDecryptPython(t *testing.T) {
	const pythonToken = "gAAAAABqIc4_cQZD1spGG0q3eUNdxrvaaMQ3Qc5wgCFc2gLVTlW8SUmb8RJbLhAKi2BUzRDFfR2GP5Dl8tGSGrZlabkvERn5E2hiO6UWb6J4sFNdh1lBqjQ="

	got, err := FernetDecrypt(testKey(), pythonToken)
	require.NoError(t, err)
	require.Equal(t, "JBSWY3DPEHPK3PXP", got)
}

// TestFernetDecryptWrongKeyFails ensures a token encrypted under one key does
// not decrypt under another (authentication tag mismatch).
func TestFernetDecryptWrongKeyFails(t *testing.T) {
	key := testKey()
	tok, err := FernetEncrypt(key, "secret")
	require.NoError(t, err)

	wrong := make([]byte, 32)
	for i := range wrong {
		wrong[i] = 0xFF
	}
	_, err = FernetDecrypt(wrong, tok)
	require.ErrorIs(t, err, ErrFernetDecrypt)
}

// TestFernetDecryptGarbageFails ensures malformed input returns ErrFernetDecrypt.
func TestFernetDecryptGarbageFails(t *testing.T) {
	_, err := FernetDecrypt(testKey(), "not-a-fernet-token")
	require.ErrorIs(t, err, ErrFernetDecrypt)
}
