"""Load the build-time test catalog.

The catalog itself lives in ``manifest.json`` next to this module, generated by
``scripts/generate-tests-manifest.py`` from the explicit allowlist of pytest
e2e files. If the JSON is missing (fresh checkout, never generated), an empty
catalog is returned rather than raising — the frontend renders an empty state.
"""

from __future__ import annotations

import json
import logging
import threading
from pathlib import Path
from typing import Any

from .schemas import Catalog

logger = logging.getLogger(__name__)

_MANIFEST_PATH = Path(__file__).with_name("manifest.json")

# Explicit allowlist of pytest e2e files used by the generator.
# (family, source_file_basename, attribute_name_inside_module, schema)
# schema: "dict"  → { rule_id: payload_string } — payload sent as ?param=
# schema: "list"  → list[{rule_id, url, params, headers}] — uses fields directly
MANIFEST_SOURCES: list[tuple[str, str, str, str]] = [
    ("xss", "test_xss_941.py", "xss_payloads", "dict"),
    ("sqli", "test_sqli_942.py", "sqli_payloads", "dict"),
    ("rce", "test_rce_932.py", "rce_payloads", "dict"),
    ("rfi", "test_rfi_931.py", "rfi_payloads", "dict"),
    ("scanner", "test_scanner_913.py", "scanner_payloads", "dict"),
    ("java", "test_java_944.py", "java_payloads", "dict"),
    ("php", "test_php_933.py", "php_payloads", "dict"),
    ("session_fixation", "test_session_fixation_943.py", "session_fixation_payloads", "dict"),
    ("multipart", "test_multipart_922.py", "multipart_payloads", "dict"),
    ("method", "test_method_911.py", "method_payloads", "dict"),
    ("protocol_attack", "test_protocol_attack_921.py", "protocol_payloads", "dict"),
    ("protocol_enforce", "test_protocol_enforcement_920.py", "protocol_payloads", "dict"),
    ("generic", "test_generic_934.py", "generic_payloads", "dict"),
    ("blocking", "test_blocking_949.py", "blocking_payloads", "dict"),
    ("lfi", "test_lfi_930.py", "lfi_test_cases", "list"),
]


_cache_lock = threading.Lock()
_cached: Catalog | None = None


def load_catalog(force: bool = False) -> Catalog:
    """Return the catalog, loading from disk on first call.

    The catalog rarely changes at runtime (it's a build-time artifact), so we
    keep a single in-memory copy. Pass ``force=True`` to bypass the cache.
    """
    global _cached
    with _cache_lock:
        if _cached is not None and not force:
            return _cached
        _cached = _load_from_disk()
        return _cached


def _load_from_disk() -> Catalog:
    if not _MANIFEST_PATH.exists():
        logger.warning(
            "tests manifest.json missing at %s — Tests catalog will be empty. "
            "Run scripts/generate-tests-manifest.py to populate it.",
            _MANIFEST_PATH,
        )
        return Catalog(tests=[])

    try:
        raw: dict[str, Any] = json.loads(_MANIFEST_PATH.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        logger.exception("Failed to load tests manifest.json: %s", exc)
        return Catalog(tests=[])

    try:
        return Catalog.model_validate(raw)
    except Exception:
        logger.exception("Tests manifest.json failed schema validation; returning empty")
        return Catalog(tests=[])
