server {
    listen 80;
    server_name zwarder.ru;

    root /var/www/test_mode1;
    index index.html;

    include locations.conf;
}
server {
    listen 80;
    server_name test.ru;

    root /var/www/test_mode1;
    index index2.html;

    include locations.conf;
}
