apiVersion: 1

datasources:
  - name: ClickHouse
    type: clickhouse
    access: proxy
    orgId: 1
    url: http://clickhouse:8123
    database: waf
    user: default
    secure: false
    jsonData:
      httpMethod: POST
      queryTimeout: 30
      maxConcurrentQueries: 10
      customHttpHeaders: {}
      customQueryParameters: {}
    version: 1
    editable: false
    isDefault: true
    jsonDataAuthType: none