## Connection: pizda (ID: 4)
## Mode: static
## Generated at: 2026-05-08T00:18:17.961408Z

server {
    listen 80;
    server_name demo.waf.local;

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name demo.waf.local;

    ssl_certificate /etc/angie/http.d/conn_4/4.crt;
    ssl_certificate_key /etc/angie/http.d/conn_4/4.key;

    # ModSecurity integration
    modsecurity on;
    modsecurity_rules_file /etc/angie/modsecurity/rules.conf;

    location / {
        root /etc/angie/http.d/conn_4/site;
        index index.html index.htm;
        try_files $uri $uri/ =404;
    }
}