apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: bfbcca0459mo0f
    access: proxy
    orgId: 1
    database: logs
    secure: false
    jsonData:
      protocol: http
      port: 8123
      host: clickhouse
      username: user_434d675d
    version: 1
    editable: false
    isDefault: true
    jsonDataAuthType: none
    secureJsonData:
      password: 5YilCXuCuDUFVZ4xqfohQRnA7ObxWAhQ