apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: bfbcca0459mo0f
    access: proxy
    orgId: 1
    database: waf
    secure: false
    jsonData:
      protocol: http
      port: 8123
      host: clickhouse
      username: default
    version: 1
    editable: false
    isDefault: true
    jsonDataAuthType: none
    secureJsonData:
      password: "my_secure_password"