#!/bin/sh
#
# Bootstrap the default-server TLS cert.
#
# Angie's _default.conf only listens on :80 by design — every public vhost is
# rendered by the backend with its own server_name. For requests that don't
# match any vhost (raw IP, unknown Host header) we still want :443 to answer
# with a valid TLS handshake instead of refusing the connection.
#
# This script provisions a real Let's Encrypt cert for $WAF_DEFAULT_DOMAIN
# (e.g. zwarder.ru — must already point at this WAF edge), copies it into
# the Angie config tree, materialises _default-tls.conf with a
# `listen 443 ssl default_server` block, and reloads Angie.
#
# Re-run for renewals or after WAF_DEFAULT_DOMAIN changes.
#
# Usage:
#   WAF_DEFAULT_DOMAIN=zwarder.ru ACME_EMAIL=you@example.com ./scripts/bootstrap-default-cert.sh
#   # or just: ./scripts/bootstrap-default-cert.sh zwarder.ru you@example.com

set -eu

# Run from project root so the host-side `./configs/...` path resolves
# regardless of where the caller `cd`'d to.
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR/.."

DOMAIN="${1:-${WAF_DEFAULT_DOMAIN:-}}"
EMAIL="${2:-${ACME_EMAIL:-}}"

if [ -z "$DOMAIN" ]; then
    echo "Error: domain not set. Pass as first arg or via WAF_DEFAULT_DOMAIN env." >&2
    exit 1
fi
if [ -z "$EMAIL" ]; then
    echo "Error: email not set. Pass as second arg or via ACME_EMAIL env." >&2
    exit 1
fi

# Paths inside the backend container.
BACKEND_WEBROOT="/var/lib/angie/http.d/_default/site"
BACKEND_DEFAULT_DIR="/var/lib/angie/http.d/_default"
LE_LIVE_DIR="/etc/letsencrypt/live/default"

# Paths the Angie container sees (different mount, same files on host).
ANGIE_CERT="/etc/angie/http.d/_default/default.crt"
ANGIE_KEY="/etc/angie/http.d/_default/default.key"

# Host-side path for the TLS server block.
HOST_TLS_CONF="./configs/angie/http.d/_default-tls.conf"

echo "==> Ensuring Angie is up so it can serve the ACME challenge on :80..."
docker compose up -d angie backend >/dev/null
# Give Angie a moment to bind :80 if it just came up.
sleep 2

echo "==> Requesting Let's Encrypt cert for $DOMAIN..."
docker compose exec -T backend sh -c "
    mkdir -p '$BACKEND_WEBROOT' '$BACKEND_DEFAULT_DIR' &&
    certbot certonly \
        --webroot \
        -w '$BACKEND_WEBROOT' \
        -d '$DOMAIN' \
        --non-interactive \
        --agree-tos \
        -m '$EMAIL' \
        --cert-name default \
        --key-type rsa \
        --preferred-challenges http \
        --config-dir /etc/letsencrypt \
        --work-dir /tmp/certbot-work \
        --logs-dir /tmp/certbot-logs \
        --keep-until-expiring
"

echo "==> Copying cert into the Angie config tree..."
docker compose exec -T backend sh -c "
    cp '$LE_LIVE_DIR/fullchain.pem' '$BACKEND_DEFAULT_DIR/default.crt' &&
    cp '$LE_LIVE_DIR/privkey.pem'   '$BACKEND_DEFAULT_DIR/default.key' &&
    chmod 600 '$BACKEND_DEFAULT_DIR/default.key'
"

echo "==> Writing $HOST_TLS_CONF..."
cat > "$HOST_TLS_CONF" <<EOF
# Default-server TLS fallback. Generated by scripts/bootstrap-default-cert.sh.
# Re-run that script to refresh the cert or change the domain.
#
# Catches any HTTPS request whose Host header doesn't match a per-connection
# vhost — without this, :443 would refuse the connection entirely whenever
# no conn_* server has yet been ACME-activated.
server {
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;
    http2 on;
    server_name _;

    ssl_certificate     $ANGIE_CERT;
    ssl_certificate_key $ANGIE_KEY;

    access_log /var/log/angie/geoip.log with_geoip_json;
    access_log /var/log/angie/access.log combined;

    location = /healthz {
        access_log off;
        modsecurity off;
        return 200 "ok\n";
    }

    location / {
        proxy_pass http://127.0.0.1:8081;
        proxy_set_header Host \$host;
        proxy_http_version 1.1;
    }
}
EOF

echo "==> Validating Angie config..."
docker compose exec -T angie angie -t

echo "==> Reloading Angie..."
docker compose exec -T angie angie -s reload

echo ""
echo "Done. Default :443 listener is live with the cert for $DOMAIN."
echo "Verify: curl -kI https://$DOMAIN/healthz"
