#!/bin/bash

CLICKHOUSE_USER="user_$(openssl rand -hex 4)"
CLICKHOUSE_PASSWORD=$(openssl rand -base64 24 | tr -dc 'a-zA-Z0-9' | head -c 32)

cat > .env << EOF
# Angie
ANGIE_BINARY=angie
ANGIE_CONFIG_TEMPLATE=/etc/angie/angie.conf.t
ANGIE_ERROR_LOG_SEVERITY=notice
ANGIE_FEATURE_RELOAD=on
ANGIE_FEATURE_TEMPLATE=on
ANGIE_LOAD_MODULES="modsecurity,geoip2"
ANGIE_LOAD_MODSECURITY=on
ANGIE_LOAD_GEOIP2=on
ANGIE_PID_FILE=/run/angie/angie.pid
ANGIE_WORKER_CONNECTIONS=65536
ANGIE_WORKER_RLIMIT_NOFILE=65536

# Vector
VECTOR_CONFIG=/etc/vector/vector.yaml
VECTOR_LOG=info
VECTOR_LOG_FORMAT=text
VECTOR_COLOR=auto
VECTOR_WATCH_CONFIG=false
VECTOR_REQUIRE_HEALTHY=false
VECTOR_GRACEFUL_SHUTDOWN_LIMIT_SECS=60
VECTOR_INTERNAL_LOG_RATE_LIMIT=10
VECTOR_WATCH_CONFIG_METHOD=recommended
VECTOR_WATCH_CONFIG_POLL_INTERVAL_SECONDS=60
VECTOR_STRICT_ENV_VARS=true
VECTOR_ALLOW_EMPTY_CONFIG=false
VECTOR_OPENSSL_NO_PROBE=false

# ClickHouse
CLICKHOUSE_ENDPOINT=http://clickhouse:8123
CLICKHOUSE_USER=$CLICKHOUSE_USER
CLICKHOUSE_PASSWORD=$CLICKHOUSE_PASSWORD
CLICKHOUSE_DB=waf

# Grafana
GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
EOF

echo "Generated .env file"
echo "CLICKHOUSE_USER=$CLICKHOUSE_USER"
echo "CLICKHOUSE_PASSWORD=$CLICKHOUSE_PASSWORD"