#!/bin/bash
# Generates .env with random secrets. Re-running OVERWRITES .env — back up
# first if you've already rotated passwords by hand.
#
# Why this script exists: docker-compose.yml requires GRAFANA_ADMIN_PASSWORD,
# GRAFANA_SECRET_KEY, and POSTGRES_PASSWORD via the `:?...` syntax. Without
# them the stack refuses to boot — intentional, so we never ship default
# admin/admin or weak fallbacks. See .gstack/security-reports/.

set -euo pipefail

CLICKHOUSE_USER="user_$(openssl rand -hex 4)"
CLICKHOUSE_PASSWORD=$(openssl rand -base64 24 | tr -dc 'a-zA-Z0-9' | head -c 32)
POSTGRES_PASSWORD=$(openssl rand -base64 24 | tr -dc 'a-zA-Z0-9' | head -c 32)
GRAFANA_ADMIN_PASSWORD=$(openssl rand -base64 24 | tr -dc 'a-zA-Z0-9' | head -c 24)
# secret_key encrypts cookies + stored datasource creds. Must be stable
# across restarts (rotating it re-encrypts everything in grafana.db).
GRAFANA_SECRET_KEY=$(openssl rand -base64 32 | tr -dc 'a-zA-Z0-9' | head -c 32)
# JWT signing key for backend session cookies. Stored in .env so it survives
# backend restarts — otherwise security.py falls back to an ephemeral secret
# and every restart invalidates all active sessions, forcing re-login.
WAF_JWT_SECRET=$(openssl rand -base64 48 | tr -dc 'a-zA-Z0-9' | head -c 64)
# Host docker group GID — backend container joins this group at runtime
# to access /var/run/docker.sock without running as root. Falls back to
# 999 (most Linux distros) when getent isn't available (eg. macOS hosts).
DOCKER_GID="$(getent group docker 2>/dev/null | cut -d: -f3 || echo 999)"

cat > .env << EOF
# Angie
ANGIE_BINARY=angie
ANGIE_CONFIG_TEMPLATE=/etc/angie/angie.conf.t
ANGIE_ERROR_LOG_SEVERITY=notice
ANGIE_FEATURE_RELOAD=on
ANGIE_FEATURE_TEMPLATE=on
ANGIE_LOAD_MODULES="modsecurity,geoip2"
ANGIE_LOAD_MODSECURITY=on
ANGIE_LOAD_GEOIP2=on
ANGIE_PID_FILE=/run/angie/angie.pid
ANGIE_WORKER_CONNECTIONS=65536
ANGIE_WORKER_RLIMIT_NOFILE=65536

# Vector
VECTOR_CONFIG=/etc/vector/vector.yaml
VECTOR_LOG=info
VECTOR_LOG_FORMAT=text
VECTOR_COLOR=auto
VECTOR_WATCH_CONFIG=false
VECTOR_REQUIRE_HEALTHY=false
VECTOR_GRACEFUL_SHUTDOWN_LIMIT_SECS=60
VECTOR_INTERNAL_LOG_RATE_LIMIT=10
VECTOR_WATCH_CONFIG_METHOD=recommended
VECTOR_WATCH_CONFIG_POLL_INTERVAL_SECONDS=60
VECTOR_STRICT_ENV_VARS=true
VECTOR_ALLOW_EMPTY_CONFIG=false
VECTOR_OPENSSL_NO_PROBE=false

# ClickHouse
CLICKHOUSE_ENDPOINT=http://clickhouse:8123
CLICKHOUSE_USER=$CLICKHOUSE_USER
CLICKHOUSE_PASSWORD=$CLICKHOUSE_PASSWORD
CLICKHOUSE_DB=logs

# PostgreSQL (backend metadata: users, connections)
POSTGRES_USER=waf
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=waf

# Grafana - required by docker-compose.yml grafana service.
GRAFANA_ADMIN_PASSWORD=$GRAFANA_ADMIN_PASSWORD
GRAFANA_SECRET_KEY=$GRAFANA_SECRET_KEY
# Allowed origin for Grafana Live WebSocket. Override if you serve the
# panel under a different hostname.
GRAFANA_LIVE_ALLOWED_ORIGINS=http://localhost:3000

# Docker GID - backend container joins this host group to use docker.sock
# without running as root.
DOCKER_GID=$DOCKER_GID

# Backend JWT signing key (HS256). Stable across restarts so sessions survive.
WAF_JWT_SECRET=$WAF_JWT_SECRET

# Email registered with Let's Encrypt for ACME account + expiry notifications.
# Override on regeneration if running under a different operator.
ACME_EMAIL=zwarder.main@gmail.com

EOF

# 0600 so other users on the host can't read the secrets.
chmod 600 .env

# Re-stamp configs/clickhouse/users.d/default-user.xml so the <user_*> tag
# matches the freshly-rolled $CLICKHOUSE_USER. This file replaces the one
# that clickhouse/clickhouse-server's entrypoint would normally auto-write
# (we set CLICKHOUSE_SKIP_USER_SETUP=1 in docker-compose.yml so entrypoint
# leaves ours alone). It adds an explicit `<grants>GRANT NAMED COLLECTION
# ON postgres_waf</grants>` block so the user can use the postgres_waf
# named collection defined in config.d/named_collections.xml — without
# that grant, logs.connection_domains fails with ACCESS_DENIED and the
# Grafana `Domain` template variable goes blank.
mkdir -p configs/clickhouse/users.d
cat > configs/clickhouse/users.d/default-user.xml << EOF
<!--
  AUTO-GENERATED by scripts/generate-env.sh. Do not hand-edit; the
  <user_*> tag and <password> must match .env. Re-run generate-env.sh
  to regenerate after rolling credentials.
-->
<clickhouse>
  <users>
    <default remove="remove"></default>

    <$CLICKHOUSE_USER>
      <profile>default</profile>
      <networks>
        <ip>::/0</ip>
      </networks>
      <password><![CDATA[$CLICKHOUSE_PASSWORD]]></password>
      <quota>default</quota>
      <grants>
        <!-- GRANT ALL restores the implicit-superuser baseline the user
             had before we declared <grants> — declaring grants narrows
             the user to exactly what's listed otherwise. -->
        <query>GRANT ALL ON *.*</query>
        <query>GRANT NAMED COLLECTION ON postgres_waf</query>
      </grants>
    </$CLICKHOUSE_USER>
  </users>
</clickhouse>
EOF

echo "Generated .env file (mode 0600)"
echo "  CLICKHOUSE_USER=$CLICKHOUSE_USER"
echo "  GRAFANA_ADMIN_PASSWORD=$GRAFANA_ADMIN_PASSWORD"
echo "  (POSTGRES_PASSWORD, GRAFANA_SECRET_KEY, CLICKHOUSE_PASSWORD - see .env)"
echo "  DOCKER_GID=$DOCKER_GID"
echo "  Wrote configs/clickhouse/users.d/default-user.xml for $CLICKHOUSE_USER"
