Include modsecurity.conf

# To enable the OWASP CRS, please perform the following steps:
#
# 1. Checkout Core Rule Set from GitHub and create config files as shown below:
#
#      cd /var/lib/angie/modsecurity
#      sudo git clone -b v3.3.5 -c advice.detachedHead=false https://github.com/coreruleset/coreruleset
#      sudo cp coreruleset/crs-setup.conf.example coreruleset/crs-setup.conf
#      sudo cp coreruleset/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf.example \
#              coreruleset/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf
#      sudo cp coreruleset/rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf.example \
#              coreruleset/rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf
#
# 2. Uncomment both 'Include' directives below

Include /var/lib/angie/modsecurity/coreruleset/crs-setup.conf
Include /var/lib/angie/modsecurity/coreruleset/rules/*.conf

SecRule REQUEST_URI "@rx .*" "id:1001,phase:1,log,auditlog,pass,status:200"

# Force audit logging in DetectionOnly mode when an anomaly score > 0 is detected.
# This ensures that malicious requests are captured in logs and visible in the UI
# even when WAF is not actively blocking them.
SecRule TX:anomaly_score "@gt 0" "id:200010,phase:2,t:none,nolog,pass,ctl:auditEngine=On"
SecRule TX:anomaly_score "@gt 0" "id:200011,phase:5,t:none,nolog,pass,ctl:auditEngine=On"
